// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfQWlSQnSI0zcbNlF5cLJ4I6cHojvesrc',
    appId: '1:636542043054:web:c429e75f4412a7999a7e3f',
    messagingSenderId: '636542043054',
    projectId: 'whatsapp-f1da1',
    authDomain: 'whatsapp-f1da1.firebaseapp.com',
    storageBucket: 'whatsapp-f1da1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbAKURXZ7XjpCJFnyN2RyM6YAB_Q0ME54',
    appId: '1:636542043054:android:24455a6c41b326599a7e3f',
    messagingSenderId: '636542043054',
    projectId: 'whatsapp-f1da1',
    storageBucket: 'whatsapp-f1da1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChnKoqacOCdYppWB-HblZXv0uvaUAdky8',
    appId: '1:636542043054:ios:067f8b18bdbd75719a7e3f',
    messagingSenderId: '636542043054',
    projectId: 'whatsapp-f1da1',
    storageBucket: 'whatsapp-f1da1.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChnKoqacOCdYppWB-HblZXv0uvaUAdky8',
    appId: '1:636542043054:ios:ef4d2e473748bdee9a7e3f',
    messagingSenderId: '636542043054',
    projectId: 'whatsapp-f1da1',
    storageBucket: 'whatsapp-f1da1.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
